language: shell # (unofficial)
sudo: false

os:
  - linux
  - osx
env:
  # outdated/legacy
  - TEST_SHELL=sh BORG=1.0.2 BORG_SOURCE=binary # old, Ubuntu Xenial
  # stable
  # - TEST_SHELL=sh BORG=stable BORG_VARIANT=borg-linux64 BORG_SOURCE=binary # stable, unsupported by current TravisCi config
  - TEST_SHELL=zsh BORG=1.0.11 BORG_SOURCE=binary # up-to-date/stable
  - TEST_SHELL=bash BORG=1.0.11 BORG_SOURCE=binary # up-to-date/stable
  # more up-to-date
  - TEST_SHELL=sh BORG=1.1.0rc3 BORG_SOURCE=binary # bleeding edge/RC
  # - TEST_SHELL=sh BORG=nightly # dev version, unsupported by current TravisCi config
before_script:
  # add custom binary path
  - mkdir "$PWD/custombin/"
  - export PATH="$PWD/custombin/:$PATH"
  # install packages on OS X
  # - 'if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi' # disabled, as packages may already be there
  - 'if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install shellcheck zsh; brew upgrade gpg; alias gpg="gpg2"; fi'
  # set correct binary variant
  - 'if [ "$TRAVIS_OS_NAME" = "osx" ]; then export BORG_VARIANT=borg-macosx64; fi'
  - 'if [ "$TRAVIS_OS_NAME" = "linux" ]; then export BORG_VARIANT=borg-linux64; fi'
  # installing borg
  - tests/helper/installBorg.sh
  # install shunit2
  - cd tests&&git clone https://github.com/kward/shunit2&&cd ..

script:
  - tests/helper/verifySignature.sh
  - $TEST_SHELL tests/helper/helperCheckVersion.sh
  - tests/testShellcheck.sh
  - tests/unitTests/borgcronStarter.sh
  - tests/unitTests/borgcron.sh
  - tests/unitTests/borgcronReal.sh
  - tests/unitTests/checkLastBackup.sh

addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck
    # shells to check
    - zsh

matrix:
  allow_failures:
  - env: BORG=nightly

notifications:
  email:
    on_success: change
    on_failure: change
