language: shell
sudo: false
dist: trusty

env:
  # - SHELL=sh BORG=stable BORG_VARIANT=borg-linux64 BORG_SOURCE=binary # stable unsupported by TravisCi
  - SHELL=sh BORG=1.0.2 BORG_SOURCE=binary BORG_VARIANT=borg-linux64 # old, Ubuntu Xenial
  - SHELL=sh BORG=1.0.11 BORG_SOURCE=binary BORG_VARIANT=borg-linux64 # up-to-date/stable
  - SHELL=sh BORG=1.1.0rc3 BORG_SOURCE=binary BORG_VARIANT=borg-linux64 # bleeding edge/RC
  - SHELL=sh BORG=nightly BORG_SOURCE=pip # dev version
before_script:
  # add custom binary path
  - mkdir "$PWD/custombin/"
  - export PATH="$PATH:$PWD/custombin/"
  # installing borg
  - tests/helper/installBorg.sh

script:
  - tests/helper/verifySignature.sh
  - tests/helper/helperCheckVersion.sh
  - tests/testShellcheck.sh

addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck

matrix:
  allow_failures:
  - env: SHELL=sh BORG=nightly

notifications:
  email:
    on_success: change
    on_failure: change
