language: shell # (unofficial)
sudo: false
dist: trusty

env:
  # - TEST_SHELL=sh BORG=stable BORG_VARIANT=borg-linux64 BORG_SOURCE=binary # stable, unsupported by TravisCi
  - TEST_SHELL=sh BORG=1.0.2 BORG_SOURCE=binary BORG_VARIANT=borg-linux64 # old, Ubuntu Xenial
  - TEST_SHELL=zsh BORG=1.0.11 BORG_SOURCE=binary BORG_VARIANT=borg-linux64 # up-to-date/stable
  - TEST_SHELL=bash BORG=1.0.11 BORG_SOURCE=binary BORG_VARIANT=borg-linux64 # up-to-date/stable
  - TEST_SHELL=sh BORG=1.1.0rc3 BORG_SOURCE=pip # bleeding edge/RC
  - TEST_SHELL=sh BORG=nightly # dev version, not yet implemented
before_script:
  # add custom binary path
  - mkdir "$PWD/custombin/"
  - export PATH="$PATH:$PWD/custombin/"
  # installing borg
  - tests/helper/installBorg.sh

script:
  - tests/helper/verifySignature.sh
  - $TEST_SHELL tests/helper/helperCheckVersion.sh
  - tests/testShellcheck.sh
  # - $TEST_SHELL tests/testUnit.sh

addons:
  apt:
    # sources:
    # - debian-sid
    packages:
    - shellcheck
    - zsh
    # dependencies for pip/git
    - python3 python3-dev python3-pip python-virtualenv
    - libssl-dev openssl libacl1-dev libacl1 liblz4-dev liblz4-1
    - libzmq3-dev libzmq3 build-essential
    # for FUSE
    - libfuse-dev fuse pkg-config

matrix:
  allow_failures:
  - env: BORG=nightly

notifications:
  email:
    on_success: change
    on_failure: change
